"""create projects and vulnerabilities

Revision ID: 85e9f9518d10
Revises: 
Create Date: 2026-09-24 01:10:35.189861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85e9f9518d10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Человекочитаемое имя проекта'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="URL-safe идентификатор, например 'backend-api'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Опциональное описание проекта'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('vulnerabilities',
    sa.Column('title', sa.String(length=500), nullable=False, comment="Краткое название, например 'SQL Injection in login endpoint'"),
    sa.Column('description', sa.Text(), nullable=False, comment='Полное описание уязвимости'),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='severity_level'), nullable=False, comment='Уровень критичности по CVSS'),
    sa.Column('cvss', sa.Float(), nullable=True, comment='CVSS v3.1 base score, 0.0–10.0'),
    sa.Column('cwe', sa.Integer(), nullable=True, comment='CWE-ID, например 89 для SQL Injection'),
    sa.Column('cve_id', sa.String(length=20), nullable=True, comment='CVE-ID, например CVE-2024-1234'),
    sa.Column('status', sa.Enum('open', 'triaged', 'in_progress', 'resolved', 'false_positive', 'wont_fix', name='vulnerability_status'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scanner', sa.String(length=50), nullable=True, comment='bandit | semgrep | zap | manual'),
    sa.Column('scanner_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Сырой вывод сканера — для аудита и воспроизведения'),
    sa.Column('resolution_note', sa.Text(), nullable=True, comment='Комментарий AppSec-инженера при закрытии'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_vulnerabilities_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerabilities'))
    )
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_id'), 'vulnerabilities', ['id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_project_id'), 'vulnerabilities', ['project_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_status'), 'vulnerabilities', ['status'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_title'), 'vulnerabilities', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_title'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_status'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_project_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
