"""add github_repo and default_target to projects

Revision ID: e74d240d4372
Revises: db2669c01be1
Create Date: 2026-10-04 02:14:49.461145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74d240d4372'
down_revision: Union[str, Sequence[str], None] = 'db2669c01be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_repo', sa.String(length=255), nullable=True, comment="GitHub repo в формате 'org/repo'. Используется для webhook'ов."))
    op.add_column('projects', sa.Column('default_target', sa.String(length=500), nullable=True, comment="Путь внутри worker-контейнера для сканирования по webhook'у"))
    op.create_index(op.f('ix_projects_github_repo'), 'projects', ['github_repo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_github_repo'), table_name='projects')
    op.drop_column('projects', 'default_target')
    op.drop_column('projects', 'github_repo')
    # ### end Alembic commands ###
